# Data Visualizations

In [1]:
import plotly.express as px
import plotly.io as pio

pio.renderers.default = 'notebook'

In [8]:
iris = px.data.iris()
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [6]:
import numpy as np

In [7]:
np.unique(df['species'])

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [14]:
fig = px.scatter(iris, x="petal_length", y="petal_width", color="species", title='Comparing Petal Length vs Petal Width of Iris flowers')
fig.update_layout(width=500, height=400)
fig.update_xaxes(title_text="Petal Length (cm)")
fig.update_yaxes(title_text="Petal Width (cm)")
fig.show()

In [1]:
import plotly.express as px
import plotly.io as pio 

pio.renderers.default = 'notebook'

In [2]:
df = px.data.iris()
df.head()

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [35]:
fig = px.scatter(df, x='sepal_length', y='sepal_width', color='species', title='Sepal Width vs Sepal Length')
fig.update_layout(
    legend=dict(
        orientation='h',
        x=0.5, y=1,
        xanchor="center", yanchor="bottom"
    )
)
fig.show()