<div style="
    background: linear-gradient(135deg, #4f1d7f 0%, #7c3aed 100%);
    color: white;
    padding: 38px 42px;
    border-radius: 18px;
    margin-bottom: 22px;
    box-shadow: 0 10px 30px rgba(0,0,0,0.15);
">
    <div style="
        display:inline-block;
        background:rgba(255,255,255,0.18);
        padding:6px 14px;
        border-radius:20px;
        font-size:13px;
        font-weight:bold;
        letter-spacing:0.5px;
        margin-bottom:12px;
    ">
        INTRO TO DATA ANALYTICS • PYTHON FOUNDATIONS
</div>

<h1 style="
        margin:0;
        font-size:38px;
        line-height:1.15;
        color:white;
">
        🐼 Pandas Series & DataFrames
</h1>

<p style="
        margin:12px 0 0 0;
        font-size:17px;
        line-height:1.55;
        max-width:900px;
">
        Learn how Pandas organizes one-dimensional and tabular data,
        how labels differ from positions, and how to select, slice, clean,
        inspect, and reorganize data for analysis.
</p>
</div>

<div style="
    border-left:5px solid #7c3aed;
    background:#f7f4ff;
    padding:18px 22px;
    border-radius:12px;
    margin:10px 0 22px 0;
">
<h3 style="margin-top:0;">🎯 Learning Objectives</h3>

By the end of this notebook, you should be able to:

- Explain what a **Pandas Series** and **Pandas DataFrame** represent.
- Create a Series from a list or dictionary.
- Distinguish between an **index label** and an **integer position**.
- Create and replace custom Series indices.
- Explain why Series index labels may contain **duplicates**.
- Use **`.loc[]`** for label-based selection and **`.iloc[]`** for position-based selection.
- Slice Series and DataFrames using both named labels and numbered positions.
- Apply vectorized string operations with the **`.str` accessor**.
- Create a DataFrame from a dictionary.
- Read a CSV file with **`pd.read_csv()`**.
- Explain how individual DataFrame rows and columns can be represented as Series.
- Use `head()`, `tail()`, `drop()`, `rename()`, and `sort_values()`.

<div style="
    background:#eef6ff;
    border:1px solid #cfe4ff;
    padding:16px 20px;
    border-radius:12px;
    margin-bottom:24px;
">
<strong>💡 Two core Pandas structures</strong>

| Structure | Dimensions | Mental Model | Example |
|---|---:|---|---|
| **Series** | 1D | One labeled column of values | student scores |
| **DataFrame** | 2D | A table of rows and columns | spreadsheet-like dataset |

A DataFrame is built from labeled data, and each individual **column** is a Pandas Series.
</div>

<div style="
    background: linear-gradient(135deg, #4f1d7f 0%, #7c3aed 100%);
    color: white;
    padding: 22px 26px;
    border-radius: 16px;
    margin: 34px 0 18px 0;
    box-shadow: 0 8px 22px rgba(79,29,127,0.18);
">
    <div style="font-size:13px; font-weight:700; letter-spacing:0.7px; opacity:0.9; margin-bottom:5px;">
        SECTION 1
    </div>
    <h2 style="margin:0; font-size:28px; color:white;">🚀 Getting Started with Pandas</h2>
    <p style="margin:8px 0 0 0; font-size:15px; line-height:1.5; opacity:0.95;">Import Pandas and become familiar with the standard alias.</p>
</div>

Pandas is one of the most widely used Python libraries for data analysis.

The conventional import statement is:

In [1]:
import pandas as pd

<div style="
    background:#f7f4ff;
    border:1px solid #ddd0f7;
    border-left:5px solid #7c3aed;
    padding:17px 20px;
    border-radius:12px;
    margin:16px 0 20px 0;
">
<strong>📌 Why <code>pd</code>?</strong><br>
<div style="margin-top:7px; line-height:1.6;">
The alias <code>pd</code> is a convention used throughout the Python data-analysis community. It keeps expressions such as <code>pd.Series()</code>, <code>pd.DataFrame()</code>, and <code>pd.read_csv()</code> concise.
</div>
</div>

<div style="
    background: linear-gradient(135deg, #4f1d7f 0%, #7c3aed 100%);
    color: white;
    padding: 22px 26px;
    border-radius: 16px;
    margin: 34px 0 18px 0;
    box-shadow: 0 8px 22px rgba(79,29,127,0.18);
">
    <div style="font-size:13px; font-weight:700; letter-spacing:0.7px; opacity:0.9; margin-bottom:5px;">
        SECTION 2
    </div>
    <h2 style="margin:0; font-size:28px; color:white;">📍 Pandas Series</h2>
    <p style="margin:8px 0 0 0; font-size:15px; line-height:1.5; opacity:0.95;">A one-dimensional collection whose values are identified by labels and positions.</p>
</div>

## 2.1 What is a Pandas Series?

A **Pandas Series** is a one-dimensional collection of values.

Each value can be accessed in two different ways:

1. By its **index label** (named index)
2. By its **integer position** (numbered index)

If you do not supply index labels, Pandas creates labels `0, 1, 2, ...`.

In [2]:
scores = pd.Series([85, 92, 78, 95])
scores

0    85
1    92
2    78
3    95
dtype: int64

The Series has four values. By default, its labels happen to look exactly like its positions i.e, `0`, `1`, `2` and `3`.

Let's inspect the index and the values separately.

In [4]:
print("Index labels:", scores.index)
print("Values:", scores.values)

Index labels: RangeIndex(start=0, stop=4, step=1)
Values: [85 92 78 95]

<div style="
    background:#fffbeb;
    border:1px solid #fde68a;
    border-left:5px solid #d97706;
    padding:17px 20px;
    border-radius:12px;
    margin:16px 0 20px 0;
">
<strong>⚠️ Label vs. position</strong><br>
<div style="margin-top:7px; line-height:1.6;">
A Series always has integer <strong>positions</strong> <code>0, 1, 2, ...</code>. Its <strong>index labels</strong> can instead be names, dates, numbers, or other values. Do not assume a label and a position are the same thing.
</div>
</div>

## 2.2 Creating a Series with Named Index Labels

Use the `index=` argument to provide your own labels.

In [5]:
student_scores = pd.Series(
    [85, 92, 78, 95],
    index=["Alice", "Bob", "Charlie", "David"]
)

student_scores

Alice      85
Bob        92
Charlie    78
David      95
dtype: int64

The Series now has:

| Position | Index label | Value |
|---:|---|---:|
| `0` | `"Alice"` | `85` |
| `1` | `"Bob"` | `92` |
| `2` | `"Charlie"` | `78` |
| `3` | `"David"` | `95` |

## 2.3 Setting or Replacing a Series Index

You can assign a new sequence of labels to `.index`.

In [6]:
temperatures = pd.Series([72, 75, 70, 68])
temperatures

0    72
1    75
2    70
3    68
dtype: int64

In [7]:
temperatures.index = ["Monday", "Tuesday", "Wednesday", "Thursday"]
temperatures

Monday       72
Tuesday      75
Wednesday    70
Thursday     68
dtype: int64

<div style="
    background:#f0fdf4;
    border:1px solid #bbf7d0;
    border-left:5px solid #16a34a;
    padding:17px 20px;
    border-radius:12px;
    margin:16px 0 20px 0;
">
<strong>✅ Index length must match</strong><br>
<div style="margin-top:7px; line-height:1.6;">
If a Series contains four values, the replacement index must also contain exactly four labels.
</div>
</div>

## 2.4 Creating a Series from a Dictionary

A Python dictionary maps keys to values.

When a dictionary is converted to a Series:

- dictionary **keys** become index labels
- dictionary **values** become Series values

In [8]:
population_dict = {
    "Texas": 31.3,
    "California": 39.4,
    "Florida": 23.4
}

population = pd.Series(population_dict)
population

Texas         31.3
California    39.4
Florida       23.4
dtype: float64

## 2.5 Duplicate Index Labels

A Pandas Series **may have duplicate index labels**.

In [9]:
regional_sales = pd.Series(
    [120, 150, 90, 175],
    index=["East", "West", "East", "North"]
)

regional_sales

East     120
West     150
East      90
North    175
dtype: int64

<div style="
    background:#eef6ff;
    border:1px solid #cfe4ff;
    border-left:5px solid #2563eb;
    padding:17px 20px;
    border-radius:12px;
    margin:16px 0 20px 0;
">
<strong>🔎 Important terminology</strong><br>
<div style="margin-top:7px; line-height:1.6;">
The label <code>"East"</code> appears twice, so the <strong>index labels are not unique</strong>. However, every element still occupies one unique integer <strong>position</strong>: <code>0</code>, <code>1</code>, <code>2</code>, or <code>3</code>.
</div>
</div>

In [11]:
regional_sales.loc["East"]

East    120
East     90
dtype: int64

## 2.6 Selecting Values with `.loc[]`

`.loc[]` means **locate by label**.

In [12]:
student_scores

Alice      85
Bob        92
Charlie    78
David      95
dtype: int64

In [13]:
student_scores.loc["Bob"]

np.int64(92)

You can also request several labels at once by passing a list.

In [14]:
student_scores.loc[["Alice", "David"]]

Alice    85
David    95
dtype: int64

## 2.7 Selecting Values with `.iloc[]`

`.iloc[]` means **integer-location**.

It uses integer positions, beginning with position `0`.

In [15]:
student_scores.iloc[0]

np.int64(85)

In [16]:
student_scores.iloc[2]

np.int64(78)

In [17]:
student_scores.iloc[[0, 3]]

Alice    85
David    95
dtype: int64

<div style="
    background:#f7f4ff;
    border:1px solid #ddd0f7;
    padding:18px 20px;
    border-radius:12px;
    margin:18px 0 22px 0;
">
<strong>🧭 .loc[] vs .iloc[]</strong>

| Selector | Uses | Series Example |
|---|---|---|
| `.loc[]` | **labels** | `student_scores.loc["Bob"]` |
| `.iloc[]` | **integer positions** | `student_scores.iloc[1]` |

A helpful memory trick:

- **loc → label**
- **iloc → integer location**
</div>

## 2.8 Slicing a Series by Numbered Position

Use `.iloc[start:stop]`.

Just like normal Python slicing, the **stop position is excluded**.

In [18]:
student_scores

Alice      85
Bob        92
Charlie    78
David      95
dtype: int64

In [19]:
student_scores.iloc[1:3]

Bob        92
Charlie    78
dtype: int64

The expression above includes positions `1` and `2`, but not position `3`.

In [20]:
student_scores.iloc[:2]

Alice    85
Bob      92
dtype: int64

In [21]:
student_scores.iloc[2:]

Charlie    78
David      95
dtype: int64

You can also use a step.

In [22]:
student_scores.iloc[::2]

Alice      85
Charlie    78
dtype: int64

## 2.9 Slicing a Series by Named Index Labels

Use `.loc[start_label:stop_label]`.

With label slicing, Pandas generally **includes the ending label**.

In [23]:
student_scores.loc["Bob":"David"]

Bob        92
Charlie    78
David      95
dtype: int64

<div style="
    background:#fffbeb;
    border:1px solid #fde68a;
    border-left:5px solid #d97706;
    padding:17px 20px;
    border-radius:12px;
    margin:16px 0 20px 0;
">
<strong>⭐ A major slicing difference</strong><br>
<div style="margin-top:7px; line-height:1.6;">
<code>student_scores.iloc[1:3]</code> excludes position <code>3</code>, while <code>student_scores.loc["Bob":"David"]</code> includes the ending label <code>"David"</code>.
</div>
</div>

<div style="
    background: linear-gradient(135deg, #fff7ed 0%, #fffbeb 100%);
    border:1px solid #fed7aa;
    border-left:6px solid #f97316;
    padding:19px 22px;
    border-radius:14px;
    margin:26px 0 12px 0;
">
<h3 style="margin:0 0 10px 0;">🧠 Knowledge Check — Series Basics</h3>
<ol style="margin-bottom:4px;">
<li style='margin:7px 0;'>What is the difference between an index <strong>label</strong> and an integer <strong>position</strong>?</li>
<li style='margin:7px 0;'>If <code>s.loc["East"]</code> returns two values, what does that tell you about the Series index?</li>
<li style='margin:7px 0;'>Which selector should you use to retrieve the element at integer position <code>2</code>?</li>
<li style='margin:7px 0;'>Which selector should you use to retrieve the value labeled <code>"Charlie"</code>?</li>
<li style='margin:7px 0;'>In <code>s.iloc[1:4]</code>, is position <code>4</code> included?</li>
</ol>
</div>

<details style="
    background:#ffffff;
    border:1px solid #e5e7eb;
    padding:14px 18px;
    border-radius:10px;
    margin:0 0 24px 0;
">
<summary><strong>✅ Click to reveal the answers</strong></summary>
<ol style="margin-top:12px;">
<li style='margin:7px 0;'>A label is the name stored in the Series index; a position is the element's numbered location beginning at 0.</li>
<li style='margin:7px 0;'>The label <code>"East"</code> appears more than once; Pandas permits duplicate index labels.</li>
<li style='margin:7px 0;'>Use <code>s.iloc[2]</code>.</li>
<li style='margin:7px 0;'>Use <code>s.loc["Charlie"]</code>.</li>
<li style='margin:7px 0;'>No. Position-based slicing follows normal Python slicing rules, so the stop position is excluded.</li>
</ol>
</details>

<div style="
    background: linear-gradient(135deg, #4f1d7f 0%, #7c3aed 100%);
    color: white;
    padding: 22px 26px;
    border-radius: 16px;
    margin: 34px 0 18px 0;
    box-shadow: 0 8px 22px rgba(79,29,127,0.18);
">
    <div style="font-size:13px; font-weight:700; letter-spacing:0.7px; opacity:0.9; margin-bottom:5px;">
        SECTION 3
    </div>
    <h2 style="margin:0; font-size:28px; color:white;">🔤 String Operations on a Series</h2>
    <p style="margin:8px 0 0 0; font-size:15px; line-height:1.5; opacity:0.95;">Apply familiar string operations to an entire column of text.</p>
</div>

Python string methods such as `.lower()` and `.strip()` normally operate on **one string**.

For a Pandas Series containing strings, use the **`.str` accessor**:

```python
series.str.method()
```

In [24]:
names = pd.Series([
    "  Alice Smith  ",
    "BOB JONES",
    "charlie brown",
    "Diana Prince"
])

names

0      Alice Smith
1          BOB JONES
2      charlie brown
3       Diana Prince
dtype: object

## 3.1 `str.strip()`

Remove leading and trailing whitespace from every string.

In [25]:
names.str.strip()

0      Alice Smith
1        BOB JONES
2    charlie brown
3     Diana Prince
dtype: object

## 3.2 `str.lower()` and `str.upper()`

In [26]:
names.str.lower()

0      alice smith
1          bob jones
2      charlie brown
3       diana prince
dtype: object

In [27]:
names.str.upper()

0      ALICE SMITH
1          BOB JONES
2      CHARLIE BROWN
3       DIANA PRINCE
dtype: object

## 3.3 `str.title()`

Convert each string to title case.

In [28]:
names.str.strip().str.title()

0      Alice Smith
1        Bob Jones
2    Charlie Brown
3     Diana Prince
dtype: object

## 3.4 `str.replace()`

Replace text inside every string.

In [29]:
names.str.strip().str.replace(" ", "_", regex=False)

0      Alice_Smith
1        BOB_JONES
2    charlie_brown
3     Diana_Prince
dtype: object

## 3.5 `str.contains()`

Check each string for a pattern.

The result is another Series containing `True` or `False`.

In [30]:
names.str.contains("alice", case=False)

0     True
1    False
2    False
3    False
dtype: bool

## 3.6 `str.startswith()` and `str.endswith()`

In [31]:
names.str.strip().str.startswith("A")

0     True
1    False
2    False
3    False
dtype: bool

In [32]:
names.str.strip().str.endswith("s")

0    False
1    False
2    False
3    False
dtype: bool

## 3.7 `str.len()`

Count the number of characters in each string.

In [33]:
names.str.strip().str.len()

0    11
1     9
2    13
3    12
dtype: int64

## 3.8 Chaining String Methods

Pandas operations can be chained so that the output of one step becomes the input to the next.

In [34]:
clean_names = (
    names
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

clean_names

0      alice_smith
1        bob_jones
2    charlie_brown
3     diana_prince
dtype: object

<div style="
    background:#eef6ff;
    border:1px solid #cfe4ff;
    border-left:5px solid #2563eb;
    padding:17px 20px;
    border-radius:12px;
    margin:16px 0 20px 0;
">
<strong>💡 Data-cleaning pattern</strong><br>
<div style="margin-top:7px; line-height:1.6;">
A common analytics workflow is to clean a text column by trimming whitespace, standardizing case, and replacing inconsistent characters before analysis.
</div>
</div>

<div style="
    background: linear-gradient(135deg, #fff7ed 0%, #fffbeb 100%);
    border:1px solid #fed7aa;
    border-left:6px solid #f97316;
    padding:19px 22px;
    border-radius:14px;
    margin:26px 0 12px 0;
">
<h3 style="margin:0 0 10px 0;">🧠 Knowledge Check — Series String Methods</h3>
<ol style="margin-bottom:4px;">
<li style='margin:7px 0;'>Why do Pandas string operations use <code>.str</code>?</li>
<li style='margin:7px 0;'>Which expression removes spaces from both ends of every string in a Series named <code>city</code>?</li>
<li style='margin:7px 0;'>What type of values does <code>city.str.contains('tx')</code> return?</li>
<li style='margin:7px 0;'>How would you convert every value in <code>city</code> to uppercase?</li>
</ol>
</div>

<details style="
    background:#ffffff;
    border:1px solid #e5e7eb;
    padding:14px 18px;
    border-radius:10px;
    margin:0 0 24px 0;
">
<summary><strong>✅ Click to reveal the answers</strong></summary>
<ol style="margin-top:12px;">
<li style='margin:7px 0;'><code>.str</code> tells Pandas to apply vectorized string operations across the Series.</li>
<li style='margin:7px 0;'>Use <code>city.str.strip()</code>.</li>
<li style='margin:7px 0;'>A Series of Boolean values: <code>True</code> or <code>False</code>.</li>
<li style='margin:7px 0;'>Use <code>city.str.upper()</code>.</li>
</ol>
</details>

<div style="
    background: linear-gradient(135deg, #4f1d7f 0%, #7c3aed 100%);
    color: white;
    padding: 22px 26px;
    border-radius: 16px;
    margin: 34px 0 18px 0;
    box-shadow: 0 8px 22px rgba(79,29,127,0.18);
">
    <div style="font-size:13px; font-weight:700; letter-spacing:0.7px; opacity:0.9; margin-bottom:5px;">
        SECTION 4
    </div>
    <h2 style="margin:0; font-size:28px; color:white;">📊 Pandas DataFrames</h2>
    <p style="margin:8px 0 0 0; font-size:15px; line-height:1.5; opacity:0.95;">A two-dimensional labeled table for working with real datasets.</p>
</div>

## 4.1 What is a DataFrame?

A **Pandas DataFrame** is a two-dimensional data structure organized into:

- rows
- columns
- row index labels
- column labels

It resembles a spreadsheet or a database table.

## 4.2 Creating a DataFrame from a Dictionary

One of the most common ways to create a DataFrame is from a dictionary.

Each dictionary key becomes a **column name**.

In [35]:
students = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Major": ["CS", "Math", "CS", "Physics", "Math"],
    "Score": [91, 84, 95, 77, 88],
    "Year": [2, 3, 1, 4, 2]
})

students

      Name    Major  Score  Year
0    Alice       CS     91     2
1      Bob     Math     84     3
2  Charlie       CS     95     1
3    David  Physics     77     4
4     Emma     Math     88     2

<div style="
    background:#f7f4ff;
    border:1px solid #ddd0f7;
    border-left:5px solid #7c3aed;
    padding:17px 20px;
    border-radius:12px;
    margin:16px 0 20px 0;
">
<strong>📌 Dictionary → DataFrame</strong><br>
<div style="margin-top:7px; line-height:1.6;">
The dictionary keys become DataFrame column labels. Each list becomes the values in that column. All columns must contain a compatible number of rows.
</div>
</div>

## 4.3 A DataFrame Column is a Series

Selecting one column returns a Pandas Series.

In [36]:
score_series = students["Score"]

print(type(score_series))
score_series

<class 'pandas.core.series.Series'>

0    91
1    84
2    95
3    77
4    88
Name: Score, dtype: int64

## 4.4 A Single DataFrame Row is Usually Returned as a Series

Selecting one row with `.loc[]` or `.iloc[]` normally returns a Series.

In [37]:
first_student = students.iloc[0]

print(type(first_student))
first_student

<class 'pandas.core.series.Series'>

Name     Alice
Major       CS
Score       91
Year         2
Name: 0, dtype: object

<div style="
    background:#f0fdf4;
    border:1px solid #bbf7d0;
    border-left:5px solid #16a34a;
    padding:17px 20px;
    border-radius:12px;
    margin:16px 0 20px 0;
">
<strong>🧩 Series inside a DataFrame</strong><br>
<div style="margin-top:7px; line-height:1.6;">
Every DataFrame column is a Pandas Series. When you select one individual row, Pandas also normally represents that selected row as a Series whose index contains the column names.
</div>
</div>

<div style="
    background: linear-gradient(135deg, #4f1d7f 0%, #7c3aed 100%);
    color: white;
    padding: 22px 26px;
    border-radius: 16px;
    margin: 34px 0 18px 0;
    box-shadow: 0 8px 22px rgba(79,29,127,0.18);
">
    <div style="font-size:13px; font-weight:700; letter-spacing:0.7px; opacity:0.9; margin-bottom:5px;">
        SECTION 5
    </div>
    <h2 style="margin:0; font-size:28px; color:white;">📁 Reading CSV Data</h2>
    <p style="margin:8px 0 0 0; font-size:15px; line-height:1.5; opacity:0.95;">Load an external data file into a DataFrame with one command.</p>
</div>

## 5.1 `pd.read_csv()`

CSV stands for **Comma-Separated Values**. It is a common format for tabular data.

The basic syntax is:

```python
df = pd.read_csv("filename.csv")
```

If the CSV file is inside a folder:

```python
df = pd.read_csv("data/filename.csv")
```

<div style="
    background:#eef6ff;
    border:1px solid #cfe4ff;
    border-left:5px solid #2563eb;
    padding:17px 20px;
    border-radius:12px;
    margin:16px 0 20px 0;
">
<strong>📂 Jupyter file location</strong><br>
<div style="margin-top:7px; line-height:1.6;">
A relative filename such as <code>students.csv</code> is searched for relative to the notebook's current working directory. In JupyterLab, keeping the notebook and CSV in the same folder is often the simplest approach.
</div>
</div>

### Runnable Example

The next cell creates a small CSV file so that the following `read_csv()` example works when you use **Run All**.

In [44]:
nascar = pd.read_csv("data/nascar.csv")
nascar

,Race,Year,Race/Year,Fin Pos,Start Pos,Laps Completed,Winnings,Total Cars,Car Make,Driver
0,1,1975,1,1,1,191,12035,35,Matador,BobbyAllison
1,1,1975,1,2,2,191,8135,35,Mercury,DavidPearson
2,1,1975,1,3,25,184,6535,35,Chevrolet,CecilGordon
3,1,1975,1,4,27,183,5035,35,Dodge,DaveMarcis
4,1,1975,1,5,22,178,3835,35,Ford,ElmoLangley
...,...,...,...,...,...,...,...,...,...,...
34879,898,2003,36,39,17,89,43150,43,Chevrolet,MikeSkinner
34880,898,2003,36,40,26,81,78703,43,Dodge,JeffGreen
34881,898,2003,36,41,23,72,60735,43,Chevrolet,MichaelWaltrip
34882,898,2003,36,42,22,57,67612,43,Chevrolet,JohnAndretti
34883,898,2003,36,43,37,28,62665,43,Ford,MattKenseth

<div style="
    background: linear-gradient(135deg, #4f1d7f 0%, #7c3aed 100%);
    color: white;
    padding: 22px 26px;
    border-radius: 16px;
    margin: 34px 0 18px 0;
    box-shadow: 0 8px 22px rgba(79,29,127,0.18);
">
    <div style="font-size:13px; font-weight:700; letter-spacing:0.7px; opacity:0.9; margin-bottom:5px;">
        SECTION 6
    </div>
    <h2 style="margin:0; font-size:28px; color:white;">🔎 Inspecting and Selecting Data</h2>
    <p style="margin:8px 0 0 0; font-size:15px; line-height:1.5; opacity:0.95;">Preview rows and retrieve columns, rows, or individual cells.</p>
</div>

## 6.1 `head()`

`head()` displays the first five rows by default.

In [47]:
nascar.head()

,Race,Year,Race/Year,Fin Pos,Start Pos,Laps Completed,Winnings,Total Cars,Car Make,Driver
0,1,1975,1,1,1,191,12035,35,Matador,BobbyAllison
1,1,1975,1,2,2,191,8135,35,Mercury,DavidPearson
2,1,1975,1,3,25,184,6535,35,Chevrolet,CecilGordon
3,1,1975,1,4,27,183,5035,35,Dodge,DaveMarcis
4,1,1975,1,5,22,178,3835,35,Ford,ElmoLangley

In [48]:
nascar.head(3)

,Race,Year,Race/Year,Fin Pos,Start Pos,Laps Completed,Winnings,Total Cars,Car Make,Driver
0,1,1975,1,1,1,191,12035,35,Matador,BobbyAllison
1,1,1975,1,2,2,191,8135,35,Mercury,DavidPearson
2,1,1975,1,3,25,184,6535,35,Chevrolet,CecilGordon

## 6.2 `tail()`

`tail()` displays the last five rows by default.

In [49]:
nascar.tail()

,Race,Year,Race/Year,Fin Pos,Start Pos,Laps Completed,Winnings,Total Cars,Car Make,Driver
34879,898,2003,36,39,17,89,43150,43,Chevrolet,MikeSkinner
34880,898,2003,36,40,26,81,78703,43,Dodge,JeffGreen
34881,898,2003,36,41,23,72,60735,43,Chevrolet,MichaelWaltrip
34882,898,2003,36,42,22,57,67612,43,Chevrolet,JohnAndretti
34883,898,2003,36,43,37,28,62665,43,Ford,MattKenseth

In [50]:
nascar.tail(2)

,Race,Year,Race/Year,Fin Pos,Start Pos,Laps Completed,Winnings,Total Cars,Car Make,Driver
34882,898,2003,36,42,22,57,67612,43,Chevrolet,JohnAndretti
34883,898,2003,36,43,37,28,62665,43,Ford,MattKenseth

## 6.3 Selecting One Column

Use one pair of brackets.

In [57]:
students

      Name    Major  Score  Year
0    Alice       CS     91     2
1      Bob     Math     84     3
2  Charlie       CS     95     1
3    David  Physics     77     4
4     Emma     Math     88     2

In [51]:
students["Name"]

0      Alice
1        Bob
2    Charlie
3      David
4       Emma
Name: Name, dtype: object

<div style="
    background:#f0fdf4;
    border:1px solid #bbf7d0;
    border-left:5px solid #16a34a;
    padding:17px 20px;
    border-radius:12px;
    margin:16px 0 20px 0;
">
<strong>✅ One column → Series</strong><br>
<div style="margin-top:7px; line-height:1.6;">
<code>students["Name"]</code> returns a <strong>Series</strong>.
</div>
</div>

## 6.4 Selecting Multiple Columns

Pass a **list of column names**, which requires two sets of brackets.

In [52]:
students[["Name", "Score"]]

      Name  Score
0    Alice     91
1      Bob     84
2  Charlie     95
3    David     77
4     Emma     88

<div style="
    background:#f0fdf4;
    border:1px solid #bbf7d0;
    border-left:5px solid #16a34a;
    padding:17px 20px;
    border-radius:12px;
    margin:16px 0 20px 0;
">
<strong>✅ Multiple columns → DataFrame</strong><br>
<div style="margin-top:7px; line-height:1.6;">
<code>students[["Name", "Score"]]</code> returns a <strong>DataFrame</strong>.
</div>
</div>

## 6.5 `.loc[]` with a DataFrame

The general form is:

```python
df.loc[row_labels, column_labels]
```

`.loc[]` works with **labels**.

In [58]:
students.loc[2]

Name     Charlie
Major         CS
Score         95
Year           1
Name: 2, dtype: object

In [59]:
students.loc[1, "Score"]

np.int64(84)

In [60]:
students.loc[1, ["Name", "Score"]]

Name     Bob
Score     84
Name: 1, dtype: object

## 6.6 `.iloc[]` with a DataFrame

The general form is:

```python
df.iloc[row_positions, column_positions]
```

`.iloc[]` works with **integer positions**.

In [61]:
students.iloc[0]

Name     Alice
Major       CS
Score       91
Year         2
Name: 0, dtype: object

In [62]:
students.iloc[0, 2]

np.int64(91)

`students.iloc[0, 2]` means:

- row position `0`
- column position `2`

Column position `2` is `"Score"`.

In [63]:
students.iloc[[0, 2, 4], [0, 2]]

      Name  Score
0    Alice     91
2  Charlie     95
4     Emma     88

<div style="
    background:#eef6ff;
    border:1px solid #cfe4ff;
    padding:18px 20px;
    border-radius:12px;
    margin:20px 0;
">
<strong>🧭 DataFrame selection pattern</strong>

| Goal | Example |
|---|---|
| Row by label | `df.loc[row_label]` |
| Row by position | `df.iloc[row_position]` |
| Cell by labels | `df.loc[row_label, column_label]` |
| Cell by positions | `df.iloc[row_position, column_position]` |
| Several columns by name | `df[["col1", "col2"]]` |
</div>

<div style="
    background: linear-gradient(135deg, #fff7ed 0%, #fffbeb 100%);
    border:1px solid #fed7aa;
    border-left:6px solid #f97316;
    padding:19px 22px;
    border-radius:14px;
    margin:26px 0 12px 0;
">
<h3 style="margin:0 0 10px 0;">🧠 Knowledge Check — DataFrame Selection</h3>
<ol style="margin-bottom:4px;">
<li style='margin:7px 0;'>What does <code>students["Score"]</code> return: a Series or a DataFrame?</li>
<li style='margin:7px 0;'>What does <code>students[["Name", "Score"]]</code> return?</li>
<li style='margin:7px 0;'>What are the two pieces inside <code>df.iloc[row, column]</code>?</li>
<li style='margin:7px 0;'>Which expression selects the cell at row label <code>1</code> and column label <code>"Score"</code>?</li>
<li style='margin:7px 0;'>What does <code>head(3)</code> display?</li>
</ol>
</div>

<details style="
    background:#ffffff;
    border:1px solid #e5e7eb;
    padding:14px 18px;
    border-radius:10px;
    margin:0 0 24px 0;
">
<summary><strong>✅ Click to reveal the answers</strong></summary>
<ol style="margin-top:12px;">
<li style='margin:7px 0;'>A Pandas Series.</li>
<li style='margin:7px 0;'>A Pandas DataFrame.</li>
<li style='margin:7px 0;'>The first specifies the row position; the second specifies the column position.</li>
<li style='margin:7px 0;'>Use <code>students.loc[1, "Score"]</code>.</li>
<li style='margin:7px 0;'>The first three rows of the DataFrame.</li>
</ol>
</details>

<div style="
    background: linear-gradient(135deg, #4f1d7f 0%, #7c3aed 100%);
    color: white;
    padding: 22px 26px;
    border-radius: 16px;
    margin: 34px 0 18px 0;
    box-shadow: 0 8px 22px rgba(79,29,127,0.18);
">
    <div style="font-size:13px; font-weight:700; letter-spacing:0.7px; opacity:0.9; margin-bottom:5px;">
        SECTION 7
    </div>
    <h2 style="margin:0; font-size:28px; color:white;">✂️ Slicing Series and DataFrames</h2>
    <p style="margin:8px 0 0 0; font-size:15px; line-height:1.5; opacity:0.95;">Compare position-based slices with label-based slices.</p>
</div>

## 7.1 Series: Position-Based Slicing

For `.iloc[]`, the stop position is excluded.

In [64]:
example_series = pd.Series(
    [10, 20, 30, 40, 50],
    index=["A", "B", "C", "D", "E"]
)

example_series

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [65]:
example_series.iloc[1:4]

B    20
C    30
D    40
dtype: int64

Positions `1`, `2`, and `3` are returned.

## 7.2 Series: Label-Based Slicing

For `.loc[]`, the ending label is included.

In [66]:
example_series.loc["B":"D"]

B    20
C    30
D    40
dtype: int64

Labels `"B"`, `"C"`, and `"D"` are returned.

## 7.3 DataFrame: Position-Based Slicing with `.iloc[]`

The syntax is:

```python
df.iloc[row_start:row_stop, column_start:column_stop]
```

Both stop positions are excluded.

In [67]:
students.iloc[1:4, 0:3]

      Name    Major  Score
1      Bob     Math     84
2  Charlie       CS     95
3    David  Physics     77

This selects:

- row positions `1`, `2`, and `3`
- column positions `0`, `1`, and `2`

## 7.4 Creating Named Row Indices

The current `students` DataFrame uses default row labels.

Use `.set_index()` to make a column become the row index.

In [68]:
students_by_name = students.set_index("Name")
students_by_name

           Major  Score  Year
Name
Alice         CS     91     2
Bob         Math     84     3
Charlie       CS     95     1
David    Physics     77     4
Emma        Math     88     2

Now `"Alice"`, `"Bob"`, `"Charlie"`, `"David"`, and `"Emma"` are row labels.

## 7.5 DataFrame: Label-Based Slicing with `.loc[]`

The syntax is:

```python
df.loc[row_start:row_stop, column_start:column_stop]
```

The ending labels are included.

In [69]:
students_by_name.loc["Bob":"David"]

           Major  Score  Year
Name
Bob         Math     84     3
Charlie       CS     95     1
David    Physics     77     4

In [70]:
students_by_name.loc["Bob":"David", "Major":"Score"]

           Major  Score
Name
Bob         Math     84
Charlie       CS     95
David    Physics     77

## 7.6 Named Index Does Not Remove Integer Positions

Even after assigning named row labels, `.iloc[]` still accesses rows and columns by numbered position.

In [71]:
students_by_name.iloc[1:4, 0:2]

           Major  Score
Name
Bob         Math     84
Charlie       CS     95
David    Physics     77

<div style="
    background:#fffbeb;
    border:1px solid #fde68a;
    border-left:5px solid #d97706;
    padding:17px 20px;
    border-radius:12px;
    margin:16px 0 20px 0;
">
<strong>⭐ The rule to remember</strong><br>
<div style="margin-top:7px; line-height:1.6;">
<strong>.loc</strong> follows labels; <strong>.iloc</strong> follows positions. Changing the index labels does not change the integer positions of the rows.
</div>
</div>

<div style="
    background: linear-gradient(135deg, #fff7ed 0%, #fffbeb 100%);
    border:1px solid #fed7aa;
    border-left:6px solid #f97316;
    padding:19px 22px;
    border-radius:14px;
    margin:26px 0 12px 0;
">
<h3 style="margin:0 0 10px 0;">🧠 Knowledge Check — Slicing</h3>
<ol style="margin-bottom:4px;">
<li style='margin:7px 0;'>What rows are returned by <code>df.iloc[1:4]</code>?</li>
<li style='margin:7px 0;'>If labels are <code>A, B, C, D, E</code>, what labels are returned by <code>s.loc["B":"D"]</code>?</li>
<li style='margin:7px 0;'>Does the stop position in an <code>.iloc[]</code> slice get included?</li>
<li style='margin:7px 0;'>Does the ending label in a typical <code>.loc[]</code> label slice get included?</li>
<li style='margin:7px 0;'>After setting student names as a DataFrame index, can you still use <code>.iloc[]</code>?</li>
</ol>
</div>

<details style="
    background:#ffffff;
    border:1px solid #e5e7eb;
    padding:14px 18px;
    border-radius:10px;
    margin:0 0 24px 0;
">
<summary><strong>✅ Click to reveal the answers</strong></summary>
<ol style="margin-top:12px;">
<li style='margin:7px 0;'>Rows at positions 1, 2, and 3.</li>
<li style='margin:7px 0;'><code>B</code>, <code>C</code>, and <code>D</code>.</li>
<li style='margin:7px 0;'>No.</li>
<li style='margin:7px 0;'>Yes.</li>
<li style='margin:7px 0;'>Yes. <code>.iloc[]</code> continues to use integer positions.</li>
</ol>
</details>

<div style="
    background: linear-gradient(135deg, #4f1d7f 0%, #7c3aed 100%);
    color: white;
    padding: 22px 26px;
    border-radius: 16px;
    margin: 34px 0 18px 0;
    box-shadow: 0 8px 22px rgba(79,29,127,0.18);
">
    <div style="font-size:13px; font-weight:700; letter-spacing:0.7px; opacity:0.9; margin-bottom:5px;">
        SECTION 8
    </div>
    <h2 style="margin:0; font-size:28px; color:white;">🛠️ Modifying and Organizing DataFrames</h2>
    <p style="margin:8px 0 0 0; font-size:15px; line-height:1.5; opacity:0.95;">Drop columns, rename columns, and sort rows.</p>
</div>

## 8.1 Dropping One Column

Use `drop(columns=...)`.

In [72]:
students.drop(columns="Year")

      Name    Major  Score
0    Alice       CS     91
1      Bob     Math     84
2  Charlie       CS     95
3    David  Physics     77
4     Emma     Math     88

<div style="
    background:#fffbeb;
    border:1px solid #fde68a;
    border-left:5px solid #d97706;
    padding:17px 20px;
    border-radius:12px;
    margin:16px 0 20px 0;
">
<strong>⚠️ Original DataFrame</strong><br>
<div style="margin-top:7px; line-height:1.6;">
Methods such as <code>drop()</code>, <code>rename()</code>, and <code>sort_values()</code> normally return a new DataFrame. The original object is not changed unless you assign the result.
</div>
</div>

In [73]:
students

      Name    Major  Score  Year
0    Alice       CS     91     2
1      Bob     Math     84     3
2  Charlie       CS     95     1
3    David  Physics     77     4
4     Emma     Math     88     2

## 8.2 Dropping Multiple Columns

Pass a list of column names.

In [74]:
students.drop(columns=["Major", "Year"])

      Name  Score
0    Alice     91
1      Bob     84
2  Charlie     95
3    David     77
4     Emma     88

To keep the result:

In [75]:
students_without_year = students.drop(columns="Year")
students_without_year

      Name    Major  Score
0    Alice       CS     91
1      Bob     Math     84
2  Charlie       CS     95
3    David  Physics     77
4     Emma     Math     88

## 8.3 Renaming One Column

Use a dictionary mapping the old name to the new name.

In [76]:
students.rename(columns={"Score": "ExamScore"})

      Name    Major  ExamScore  Year
0    Alice       CS         91     2
1      Bob     Math         84     3
2  Charlie       CS         95     1
3    David  Physics         77     4
4     Emma     Math         88     2

## 8.4 Renaming Multiple Columns

In [77]:
students.rename(columns={
    "Name": "StudentName",
    "Score": "ExamScore",
    "Year": "ClassYear"
})

  StudentName    Major  ExamScore  ClassYear
0       Alice       CS         91          2
1         Bob     Math         84          3
2     Charlie       CS         95          1
3       David  Physics         77          4
4        Emma     Math         88          2

## 8.5 Sorting Rows

Use `sort_values()`.

In [78]:
students.sort_values("Score")

      Name    Major  Score  Year
3    David  Physics     77     4
1      Bob     Math     84     3
4     Emma     Math     88     2
0    Alice       CS     91     2
2  Charlie       CS     95     1

Sort from largest to smallest with `ascending=False`.

In [79]:
students.sort_values("Score", ascending=False)

      Name    Major  Score  Year
2  Charlie       CS     95     1
0    Alice       CS     91     2
4     Emma     Math     88     2
1      Bob     Math     84     3
3    David  Physics     77     4

## 8.6 Sorting by Multiple Columns

The first column is the primary sort key. Later columns are used to break ties.

In [80]:
students.sort_values(
    ["Major", "Score"],
    ascending=[True, False]
)

      Name    Major  Score  Year
2  Charlie       CS     95     1
0    Alice       CS     91     2
4     Emma     Math     88     2
1      Bob     Math     84     3
3    David  Physics     77     4

<div style="
    background: linear-gradient(135deg, #fff7ed 0%, #fffbeb 100%);
    border:1px solid #fed7aa;
    border-left:6px solid #f97316;
    padding:19px 22px;
    border-radius:14px;
    margin:26px 0 12px 0;
">
<h3 style="margin:0 0 10px 0;">🧠 Knowledge Check — DataFrame Operations</h3>
<ol style="margin-bottom:4px;">
<li style='margin:7px 0;'>How do you remove the <code>"Year"</code> column?</li>
<li style='margin:7px 0;'>How do you remove both <code>"Major"</code> and <code>"Year"</code>?</li>
<li style='margin:7px 0;'>How do you rename <code>"Score"</code> to <code>"ExamScore"</code>?</li>
<li style='margin:7px 0;'>How do you sort from highest score to lowest score?</li>
<li style='margin:7px 0;'>Does <code>students.drop(columns='Year')</code> automatically change <code>students</code>?</li>
</ol>
</div>

<details style="
    background:#ffffff;
    border:1px solid #e5e7eb;
    padding:14px 18px;
    border-radius:10px;
    margin:0 0 24px 0;
">
<summary><strong>✅ Click to reveal the answers</strong></summary>
<ol style="margin-top:12px;">
<li style='margin:7px 0;'>Use <code>students.drop(columns="Year")</code>.</li>
<li style='margin:7px 0;'>Use <code>students.drop(columns=["Major", "Year"])</code>.</li>
<li style='margin:7px 0;'>Use <code>students.rename(columns={"Score": "ExamScore"})</code>.</li>
<li style='margin:7px 0;'>Use <code>students.sort_values("Score", ascending=False)</code>.</li>
<li style='margin:7px 0;'>No. Unless the result is assigned, the original DataFrame remains unchanged.</li>
</ol>
</details>

<div style="
    background: linear-gradient(135deg, #4f1d7f 0%, #7c3aed 100%);
    color: white;
    padding: 22px 26px;
    border-radius: 16px;
    margin: 34px 0 18px 0;
    box-shadow: 0 8px 22px rgba(79,29,127,0.18);
">
    <div style="font-size:13px; font-weight:700; letter-spacing:0.7px; opacity:0.9; margin-bottom:5px;">
        SECTION 9
    </div>
    <h2 style="margin:0; font-size:28px; color:white;">🧪 Practice: Put the Pieces Together</h2>
    <p style="margin:8px 0 0 0; font-size:15px; line-height:1.5; opacity:0.95;">Use a small product dataset to practice selection, slicing, and transformation.</p>
</div>

In [ ]:
products = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headphones"],
    "Category": ["Computer", "Accessory", "Accessory", "Computer", "Accessory"],
    "Price": [899.99, 24.99, 49.99, 199.99, 79.99],
    "Stock": [12, 80, 45, 20, 35]
})

products

<div style="
    background:#f7f4ff;
    border:1px solid #ddd0f7;
    border-left:5px solid #7c3aed;
    padding:18px 22px;
    border-radius:12px;
    margin:16px 0 18px 0;
">
<h3 style="margin-top:0;">✍️ Try It Yourself</h3>

Complete each task before opening the solution.

1. Display the first 3 rows.
2. Display the last 2 rows.
3. Select only the `"Product"` column.
4. Select the `"Product"` and `"Price"` columns.
5. Use `.iloc[]` to retrieve the value at row position `2`, column position `2`.
6. Use `.iloc[]` to select row positions `1` through `3`.
7. Set `"Product"` as the row index.
8. Use `.loc[]` to retrieve the `"Monitor"` row.
9. Slice from `"Mouse"` through `"Monitor"` by label.
10. Drop the `"Stock"` column.
11. Rename `"Price"` to `"UnitPrice"`.
12. Sort from highest price to lowest price.
</div>

In [ ]:
# 1. Display the first 3 rows

In [ ]:
# 2. Display the last 2 rows

In [ ]:
# 3. Select only the "Product" column

In [ ]:
# 4. Select the "Product" and "Price" columns

In [ ]:
# 5. Retrieve row position 2, column position 2 using .iloc[]

In [ ]:
# 6. Select row positions 1 through 3 using .iloc[]

In [ ]:
# 7-9. Create a Product index, then practice .loc[]

In [ ]:
# 10-12. Drop, rename, and sort

<details style="
    background:#f0fdf4;
    border:1px solid #bbf7d0;
    padding:16px 20px;
    border-radius:12px;
    margin:12px 0 24px 0;
">
<summary><strong>✅ Click to reveal the practice solutions</strong></summary>

```python
# 1
products.head(3)

# 2
products.tail(2)

# 3
products["Product"]

# 4
products[["Product", "Price"]]

# 5
products.iloc[2, 2]

# 6
products.iloc[1:4]

# 7
products_by_name = products.set_index("Product")

# 8
products_by_name.loc["Monitor"]

# 9
products_by_name.loc["Mouse":"Monitor"]

# 10
products.drop(columns="Stock")

# 11
products.rename(columns={"Price": "UnitPrice"})

# 12
products.sort_values("Price", ascending=False)
```
</details>

<div style="
    background: linear-gradient(135deg, #4f1d7f 0%, #7c3aed 100%);
    color: white;
    padding: 22px 26px;
    border-radius: 16px;
    margin: 34px 0 18px 0;
    box-shadow: 0 8px 22px rgba(79,29,127,0.18);
">
    <div style="font-size:13px; font-weight:700; letter-spacing:0.7px; opacity:0.9; margin-bottom:5px;">
        SECTION 10
    </div>
    <h2 style="margin:0; font-size:28px; color:white;">🎓 Final Knowledge Check</h2>
    <p style="margin:8px 0 0 0; font-size:15px; line-height:1.5; opacity:0.95;">Test whether you can choose the right Pandas operation.</p>
</div>

<div style="
    background: linear-gradient(135deg, #fff7ed 0%, #fffbeb 100%);
    border:1px solid #fed7aa;
    border-left:6px solid #f97316;
    padding:19px 22px;
    border-radius:14px;
    margin:26px 0 12px 0;
">
<h3 style="margin:0 0 10px 0;">🧠 Knowledge Check — Series & DataFrames</h3>
<ol style="margin-bottom:4px;">
<li style='margin:7px 0;'>A Series has labels <code>101, 105, 110</code>. Which selector guarantees you retrieve the <em>second</em> item by position?</li>
<li style='margin:7px 0;'>A Series has duplicate label <code>"TX"</code>. What can <code>s.loc["TX"]</code> return?</li>
<li style='margin:7px 0;'>Which Pandas function reads a CSV file into a DataFrame?</li>
<li style='margin:7px 0;'>What data structure is returned when you select one DataFrame column?</li>
<li style='margin:7px 0;'>Which method previews the first few rows of a DataFrame?</li>
<li style='margin:7px 0;'>Which method previews the last few rows?</li>
<li style='margin:7px 0;'>Which selector uses named row and column labels?</li>
<li style='margin:7px 0;'>Which selector uses numbered row and column positions?</li>
<li style='margin:7px 0;'>Which method removes one or more DataFrame columns?</li>
<li style='margin:7px 0;'>Which method sorts rows using values from one or more columns?</li>
</ol>
</div>

<details style="
    background:#ffffff;
    border:1px solid #e5e7eb;
    padding:14px 18px;
    border-radius:10px;
    margin:0 0 24px 0;
">
<summary><strong>✅ Click to reveal the answers</strong></summary>
<ol style="margin-top:12px;">
<li style='margin:7px 0;'>Use <code>s.iloc[1]</code>. <code>.iloc[]</code> uses position regardless of the labels.</li>
<li style='margin:7px 0;'>It can return multiple matching values because Pandas allows duplicate index labels.</li>
<li style='margin:7px 0;'>Use <code>pd.read_csv()</code>.</li>
<li style='margin:7px 0;'>A Pandas Series.</li>
<li style='margin:7px 0;'>Use <code>head()</code>.</li>
<li style='margin:7px 0;'>Use <code>tail()</code>.</li>
<li style='margin:7px 0;'>Use <code>.loc[]</code>.</li>
<li style='margin:7px 0;'>Use <code>.iloc[]</code>.</li>
<li style='margin:7px 0;'>Use <code>drop(columns=...)</code>.</li>
<li style='margin:7px 0;'>Use <code>sort_values()</code>.</li>
</ol>
</details>

<div style="
    background: linear-gradient(135deg, #4f1d7f 0%, #7c3aed 100%);
    color: white;
    padding: 22px 26px;
    border-radius: 16px;
    margin: 34px 0 18px 0;
    box-shadow: 0 8px 22px rgba(79,29,127,0.18);
">
    <div style="font-size:13px; font-weight:700; letter-spacing:0.7px; opacity:0.9; margin-bottom:5px;">
        SECTION 11
    </div>
    <h2 style="margin:0; font-size:28px; color:white;">🗂️ Quick Reference</h2>
    <p style="margin:8px 0 0 0; font-size:15px; line-height:1.5; opacity:0.95;">A compact guide for choosing the correct Pandas operation.</p>
</div>

<div style="
    background:#ffffff;
    border:1px solid #e5e7eb;
    padding:18px 22px;
    border-radius:14px;
    box-shadow:0 5px 16px rgba(0,0,0,0.06);
    margin:10px 0 22px 0;
">

| Task | Pandas Pattern |
|---|---|
| Create Series | `pd.Series(values)` |
| Create named Series | `pd.Series(values, index=labels)` |
| Create DataFrame | `pd.DataFrame(dictionary)` |
| Read CSV | `pd.read_csv("file.csv")` |
| Select by label | `.loc[...]` |
| Select by position | `.iloc[...]` |
| One column | `df["column"]` |
| Multiple columns | `df[["col1", "col2"]]` |
| First rows | `df.head()` |
| Last rows | `df.tail()` |
| Drop column(s) | `df.drop(columns=...)` |
| Rename column(s) | `df.rename(columns={...})` |
| Sort rows | `df.sort_values(...)` |
| String cleanup | `series.str.strip()` |
| Lowercase strings | `series.str.lower()` |
| Search strings | `series.str.contains(...)` |
| Make a column the index | `df.set_index("column")` |

</div>

<div style="
    background:#eef6ff;
    border:1px solid #cfe4ff;
    padding:18px 22px;
    border-radius:12px;
    margin:16px 0 22px 0;
">
<h3 style="margin-top:0;">🧭 Choosing Between `.loc[]` and `.iloc[]`</h3>

Ask yourself one question:

> **Am I identifying the data by its label or by where it sits?**

| I know... | Use |
|---|---|
| the row/column **name or label** | `.loc[]` |
| the row/column **numbered position** | `.iloc[]` |

### Slicing rule

- `.iloc[start:stop]` → **stop position excluded**
- `.loc[start_label:stop_label]` → **ending label included**
</div>

<div style="
    background: linear-gradient(135deg, #ecfdf5 0%, #eff6ff 100%);
    border:1px solid #c7e8df;
    padding:22px 26px;
    border-radius:16px;
    margin:30px 0 14px 0;
    box-shadow:0 6px 18px rgba(0,0,0,0.05);
">
<h2 style="margin-top:0;">✅ Key Takeaways</h2>

### Pandas Series
- A **Series** is a one-dimensional labeled collection.
- Every element has an integer **position**.
- Every element also has an **index label**.
- Index labels may contain **duplicates**; integer positions remain distinct.
- Use `.loc[]` to select by **label**.
- Use `.iloc[]` to select by **position**.
- Use `.str` to apply vectorized string operations.

### Pandas DataFrames
- A **DataFrame** is a two-dimensional table.
- A DataFrame can be created from a **dictionary**.
- `pd.read_csv()` reads a CSV file into a DataFrame.
- Each DataFrame **column is a Series**.
- Selecting one row normally also returns a Series.
- `head()` and `tail()` quickly preview rows.
- `drop()` removes columns.
- `rename()` changes column labels.
- `sort_values()` sorts rows by data values.
- `set_index()` creates named row labels.

### The Most Important Selection Rule
- **`.loc[]` → labels**
- **`.iloc[]` → integer positions**

### The Most Important Slicing Rule
- **`.iloc[]` stop position is excluded**
- **`.loc[]` ending label is included**

</div>

<div style="
    text-align:center;
    color:#6b7280;
    font-size:14px;
    padding:14px 0 4px 0;
">
<strong>End of Tutorial</strong><br>
Pandas Series & DataFrames • Intro to Data Analytics
</div>